CREATE TABLE TBL_PERFIL_PER (
  NUM_ID_PER INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  TXT_NOME_PER VARCHAR(50) NOT NULL,
  TXT_DESCRICAO_PER VARCHAR(100) NULL,
  TXT_ATIVO_PER VARCHAR(3) NULL,
  PRIMARY KEY(NUM_ID_PER),
  UNIQUE INDEX IX_TBL_PER_NOME(TXT_NOME_PER)
);

CREATE TABLE TBL_FORMA_PAGAMENTO_FP (
  NUM_ID_FP INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  TXT_NOME_FP VARCHAR(50) NULL,
  TXT_DESRICAO_FP VARCHAR(50) NULL,
  TXT_ATIVO_FP VARCHAR(3) NULL,
  PRIMARY KEY(NUM_ID_FP),
  UNIQUE INDEX IX_TBL_FP_NOME(TXT_NOME_FP)
);

CREATE TABLE TBL_TECNICO_TEC (
  NUM_ID_TEC INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  TXT_NOME_TEC VARCHAR(100) NULL,
  TXT_CODIGO_TEC VARCHAR(20) NULL,
  TXT_TELEFONE_TEC VARCHAR(20) NULL,
  TXT_ATIVO_TEC VARCHAR(3) NULL,
  PRIMARY KEY(NUM_ID_TEC)
);

CREATE TABLE TBL_PECA_PEC (
  NUM_ID_PEC INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  TXT_NOME_PEC VARCHAR(50) NULL,
  TXT_CODIGO_PEC VARCHAR(50) NULL,
  VAL_ULTIMA_COMPRA_PEC DOUBLE(8,2) NULL,
  DTA_ULTIMA_COMPRA_PEC DATE NULL,
  VAL_CUSTO_MEDIO_PEC DOUBLE(8,2) NULL,
  VAL_VALOR_VENDA_PEC DOUBLE(8,2) NULL,
  VAL_TOTAL_ACUMULADO_PEC DOUBLE(8,2) NULL,
  DTH_REGISTRO_PEC DATETIME NULL,
  TXT_ATIVO_PEC VARCHAR(3) NULL,
  PRIMARY KEY(NUM_ID_PEC)
);

CREATE TABLE TBL_SERVICO_SER (
  NUM_ID_SER INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  TXT_NOME_SER VARCHAR(50) NOT NULL,
  TXT_DESCRICAO_SER VARCHAR(50) NOT NULL,
  VAL_FISICA_SER DOUBLE(8,2) NOT NULL,
  VAL_JURIDICA_SER DOUBLE(8,2) NOT NULL,
  NUM_DURACAO_SER INTEGER UNSIGNED NOT NULL,
  TXT_ATIVO_SER VARCHAR(3) NOT NULL,
  PRIMARY KEY(NUM_ID_SER),
  UNIQUE INDEX IX_TBL_SER_NOME(TXT_NOME_SER)
);

CREATE TABLE TBL_EMPRESA_EMP (
  NUM_ID_EMP INTEGER UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT,
  TXT_PESSOA_EMP VARCHAR(20) NOT NULL,
  TXT_CPFCNPJ_EMP VARCHAR(16) NOT NULL,
  TXT_RAZAO_EMP VARCHAR(100) NOT NULL,
  TXT_FANTASIA_EMP VARCHAR(100) NOT NULL,
  DTA_FUNDACAO_EMP DATE NOT NULL,
  TXT_TELEFONE_EMP VARCHAR(20) NOT NULL,
  TXT_RAMAL_EMP VARCHAR(10) NOT NULL,
  TXT_FAX_EMP VARCHAR(20) NOT NULL,
  TXT_EMAIL_EMP VARCHAR(100) NOT NULL,
  TXT_SITE_EMP VARCHAR(100) NOT NULL,
  NUM_CEP_EMP INTEGER(8) UNSIGNED NOT NULL,
  TXT_LOGRADOURO_EMP VARCHAR(100) NOT NULL,
  NUM_NUMERO_EMP INTEGER UNSIGNED NOT NULL,
  TXT_COMPLEMENTO_EMP VARCHAR(50) NOT NULL,
  TXT_BAIRRO_EMP VARCHAR(50) NOT NULL,
  TXT_CIDADE_EMP VARCHAR(50) NOT NULL,
  TXT_ESTADO_EMP CHAR(2) NOT NULL,
  TXT_IM_EMP VARCHAR(20) NOT NULL,
  TXT_IE_EMP VARCHAR(20) NOT NULL,
  TXT_RG_EMP VARCHAR(20) NULL,
  VAL_MULTA_EMP DOUBLE(8,2) NOT NULL,
  VAL_JUROS_EMP DOUBLE(8,2) NOT NULL,
  DTA_REGISTRO_EMP DATE NOT NULL,
  TXT_ATIVO_EMP VARCHAR(3) NOT NULL,
  PRIMARY KEY(NUM_ID_EMP),
  UNIQUE INDEX IX_TBL_EMP_CPFCNPJ(TXT_CPFCNPJ_EMP)
);

CREATE TABLE TBL_SISTEMAOPERACIONAL_SO (
  NUM_ID_SO INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  TXT_NOME_SO VARCHAR(50) NOT NULL,
  TXT_DESCRICAO_SO VARCHAR(50) NULL,
  TXT_ATIVO_SO VARCHAR(3) NOT NULL,
  PRIMARY KEY(NUM_ID_SO),
  UNIQUE INDEX IX_TBL_SO_NOME(TXT_NOME_SO)
);

CREATE TABLE TBL_USUARIO_USU (
  NUM_ID_USU INTEGER UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT,
  TBL_PERFIL_PER_NUM_ID_PER INTEGER UNSIGNED NOT NULL,
  TBL_EMPRESA_EMP_NUM_ID_EMP INTEGER UNSIGNED ZEROFILL NOT NULL,
  TXT_NOME_USU VARCHAR(100) NOT NULL,
  TXT_TELEFONE_USU VARCHAR(20) NOT NULL,
  TXT_EMAIL_USU VARCHAR(100) NOT NULL,
  TXT_LOGIN_USU VARCHAR(20) NOT NULL,
  TXT_SENHA_USU VARCHAR(10) NOT NULL,
  TXT_ATIVO_USU VARCHAR(3) NOT NULL,
  PRIMARY KEY(NUM_ID_USU),
  INDEX FK_TBL_PER_USU(TBL_PERFIL_PER_NUM_ID_PER),
  UNIQUE INDEX IX_TBL_USU_LOGIN(TXT_LOGIN_USU),
  INDEX IX_TBL_USU_SENHA(TXT_SENHA_USU),
  INDEX IX_TBL_USU_EMAIL(TXT_EMAIL_USU),
  INDEX FK_TBL_EMP_USU(TBL_EMPRESA_EMP_NUM_ID_EMP)
);

CREATE TABLE TBL_CLIENTE_CLI (
  NUM_ID_CLI INTEGER UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT,
  TBL_USUARIO_USU_NUM_ID_USU INTEGER UNSIGNED ZEROFILL NOT NULL,
  TXT_PESSOA_CLI VARCHAR(20) NOT NULL,
  TXT_CPF_CNPJ_CLI VARCHAR(16) NOT NULL,
  TXT_RAZAO_CLI VARCHAR(100) NOT NULL,
  TXT_FANTASIA_CLI VARCHAR(100) NULL,
  DTA_NASCIMENTO_CLI DATE NULL,
  TXT_TELEFONE_CLI VARCHAR(20) NOT NULL,
  TXT_RAMAL_CLI VARCHAR(10) NULL,
  TXT_FAX_CLI VARCHAR(20) NULL,
  TXT_EMAIL_CLI VARCHAR(100) NOT NULL,
  TXT_SITE_CLI VARCHAR(100) NULL,
  NUM_CEP_CLI INTEGER(8) UNSIGNED NULL,
  TXT_LOGRADOURO_CLI VARCHAR(100) NULL,
  NUM_NUMERO_CLI INTEGER UNSIGNED NULL,
  TXT_COMPLEMENTO_CLI VARCHAR(50) NULL,
  TXT_REFERENCIA_CLI VARCHAR(50) NULL,
  TXT_BAIRRO_CLI VARCHAR(50) NULL,
  TXT_CIDADE_CLI VARCHAR(50) NULL,
  TXT_ESTADO_CLI CHAR(2) NULL,
  TXT_IM_CLI VARCHAR(20) NULL,
  TXT_IE_CLI VARCHAR(20) NULL,
  TXT_RG_CLI VARCHAR(20) NULL,
  TXT_CONTATO_CLI VARCHAR(50) NULL,
  TXT_OBSERVACAO_CLI TEXT NULL,
  DTH_ALTERACAO_CLI DATETIME NULL,
  DTH_REGISTRO_CLI DATETIME NULL,
  VAL_SALDO_CLI DOUBLE(8,2) NULL,
  TXT_TITULOABERTO_CLI VARCHAR(3) NULL,
  TXT_ATIVO_CLI VARCHAR(3) NULL,
  PRIMARY KEY(NUM_ID_CLI),
  INDEX IX_TBL_CLI_NOME(TXT_RAZAO_CLI),
  UNIQUE INDEX IX_TBL_CLI_CPFCNPJ(TXT_CPF_CNPJ_CLI),
  INDEX FK_TBL_USU_CLI(TBL_USUARIO_USU_NUM_ID_USU)
);

CREATE TABLE TBL_CONTRATO_CM (
  NUM_ID_CM INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  TBL_USUARIO_USU_NUM_ID_USU INTEGER UNSIGNED ZEROFILL NOT NULL,
  TBL_CLIENTE_CLI_NUM_ID_CLI INTEGER UNSIGNED ZEROFILL NOT NULL,
  NUM_EQUIPAMENTOS_CM INTEGER UNSIGNED NULL,
  DTA_INICIO_CM DATE NOT NULL,
  DTA_TERMINO_CM DATE NOT NULL,
  VAL_VALOR_CM DOUBLE(8,2) NOT NULL,
  NUM_DIAPAGAMENTO_CM INTEGER UNSIGNED NULL,
  TXT_ATIVO_CM VARCHAR(3) NOT NULL,
  PRIMARY KEY(NUM_ID_CM),
  INDEX FK_TBL_CLI_ID(TBL_CLIENTE_CLI_NUM_ID_CLI),
  INDEX FK_TBL_USU_ID(TBL_USUARIO_USU_NUM_ID_USU)
);

CREATE TABLE TBL_EQUIPAMENTO_EQUIP (
  NUM_ID_EQUIP INTEGER UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT,
  TBL_SISTEMAOPERACIONAL_SO_NUM_ID_SO INTEGER UNSIGNED NOT NULL,
  TBL_CLIENTE_CLI_NUM_ID_CLI INTEGER UNSIGNED ZEROFILL NOT NULL,
  TBL_USUARIO_USU_NUM_ID_USU INTEGER UNSIGNED ZEROFILL NOT NULL,
  TXT_TIPO_EQUIP VARCHAR(20) NOT NULL,
  TXT_SETOR_EQUIP VARCHAR(50) NOT NULL,
  TXT_NOMEREDE_EQUIP VARCHAR(50) NULL,
  TXT_DESCRICAO_EQUIP VARCHAR(50) NULL,
  TXT_LOGIN_EQUIP VARCHAR(20) NOT NULL,
  TXT_SENHA_EQUIP VARCHAR(20) NOT NULL,
  TXT_UTILIZADORES_EQUIP VARCHAR(50) NULL,
  NUM_HD_EQUIP INTEGER UNSIGNED NULL,
  TXT_TIPO_ARMAZENAMENTO_EQUIP VARCHAR(20) NULL,
  TXT_PROCESSADOR_EQUIP VARCHAR(20) NULL,
  NUM_MEMORIA_EQUIP INTEGER UNSIGNED NULL,
  TXT_TIPO_MEMORIA_EQUIP VARCHAR(20) NULL,
  TXT_PLACAMAE_EQUIP VARCHAR(20) NULL,
  TXT_MONITOR_EQUIP VARCHAR(20) NULL,
  TXT_APLICATIVOS_EQUIP VARCHAR(50) NULL,
  NUM_NFE_EQUIP INTEGER UNSIGNED NULL,
  DTH_REGISTRO_EQUIP DATETIME NULL,
  TXT_MARCA_EQUIP VARCHAR(50) NULL,
  TXT_MODELO_EQUIP VARCHAR(50) NULL,
  TXT_SERIAL_EQUIP VARCHAR(30) NULL,
  TXT_OBSERVACAO_EQUIP TEXT NULL,
  TXT_ATIVO_EQUIP VARCHAR(3) NULL,
  PRIMARY KEY(NUM_ID_EQUIP),
  INDEX FK_TBL_USU_ID(TBL_USUARIO_USU_NUM_ID_USU),
  INDEX FK_TBL_CLI_ID(TBL_CLIENTE_CLI_NUM_ID_CLI),
  INDEX FK_TBL_SO_ID(TBL_SISTEMAOPERACIONAL_SO_NUM_ID_SO)
);

CREATE TABLE TBL_TITULORECEBER_TR (
  NUM_ID_TR INTEGER UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT,
  TBL_EMPRESA_EMP_NUM_ID_EMP INTEGER UNSIGNED ZEROFILL NOT NULL,
  TBL_USUARIO_USU_NUM_ID_USU INTEGER UNSIGNED ZEROFILL NOT NULL,
  TBL_CLIENTE_CLI_NUM_ID_CLI INTEGER UNSIGNED ZEROFILL NOT NULL,
  DTH_EMISSAO_TR DATETIME NOT NULL,
  DTA_VENCIMENTO_TR DATE NOT NULL,
  TXT_REFERENTE_TR VARCHAR(20) NOT NULL,
  VAL_VALOR_TR DOUBLE(8,2) NOT NULL,
  VAL_JUROS_TR DOUBLE(8,2) NOT NULL,
  VAL_MULTA_TR DOUBLE(8,2) NULL,
  VAL_DESCONTO_TR DOUBLE(8,2) NOT NULL,
  VAL_FINAL_TR DOUBLE(8,2) NOT NULL,
  VAL_PAGO_TR DOUBLE(8,2) NULL,
  VAL_SALDO_TR DOUBLE(8,2) NULL,
  DTH_RECEBIDO_TR DATETIME NULL,
  TXT_STATUS_TR VARCHAR(20) NOT NULL,
  PRIMARY KEY(NUM_ID_TR),
  INDEX FK_TBL_CLI_TR(TBL_CLIENTE_CLI_NUM_ID_CLI),
  INDEX FK_TBL_USU_TR(TBL_USUARIO_USU_NUM_ID_USU),
  INDEX FK_TBL_EMP_TR(TBL_EMPRESA_EMP_NUM_ID_EMP)
);

CREATE TABLE TBL_MOVIMENTACAO_MOV (
  NUM_ID_MOV INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  TBL_EMPRESA_EMP_NUM_ID_EMP INTEGER UNSIGNED ZEROFILL NOT NULL,
  TBL_FORMA_PAGAMENTO_FP_NUM_ID_FP INTEGER UNSIGNED NOT NULL,
  TBL_USUARIO_USU_NUM_ID_USU INTEGER UNSIGNED ZEROFILL NOT NULL,
  TBL_CLIENTE_CLI_NUM_ID_CLI INTEGER UNSIGNED ZEROFILL NOT NULL,
  VAL_VALOR_MOV DOUBLE(8,2) NULL,
  TXT_REFERENTE_MOV VARCHAR NULL,
  DTH_MOVIMENTACAO_MOV DATETIME NULL,
  TXT_TIPO_MOV VARCHAR(20) NULL,
  PRIMARY KEY(NUM_ID_MOV),
  INDEX TBL_RETIRADA_RET_FKIndex1(TBL_CLIENTE_CLI_NUM_ID_CLI),
  INDEX TBL_MOVIMENTACAO_MOV_FKIndex2(TBL_USUARIO_USU_NUM_ID_USU),
  INDEX TBL_MOVIMENTACAO_MOV_FKIndex3(TBL_FORMA_PAGAMENTO_FP_NUM_ID_FP),
  INDEX TBL_MOVIMENTACAO_MOV_FKIndex4(TBL_EMPRESA_EMP_NUM_ID_EMP)
);

CREATE TABLE TBL_RECEBIMENTO_REC (
  NUM_ID_REC INTEGER UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT,
  TBL_EMPRESA_EMP_NUM_ID_EMP INTEGER UNSIGNED ZEROFILL NOT NULL,
  TBL_FORMA_PAGAMENTO_FP_NUM_ID_FP INTEGER UNSIGNED NOT NULL,
  TBL_USUARIO_USU_NUM_ID_USU INTEGER UNSIGNED ZEROFILL NOT NULL,
  TBL_CLIENTE_CLI_NUM_ID_CLI INTEGER UNSIGNED ZEROFILL NOT NULL,
  TXT_REFERENTE_REC VARCHAR(20) NULL,
  NUM_DOCUMENTO_REC INTEGER UNSIGNED NULL,
  VAL_VALOR_REC DOUBLE(8,2) NULL,
  VAL_DESCONTO_REC DOUBLE(8,2) NULL,
  VAL_RECEBIDO_REC DOUBLE(8,2) NULL,
  DTH_RECEBIMENTO_REC DATETIME NULL,
  TXT_STATUS_REC VARCHAR(20) NULL,
  PRIMARY KEY(NUM_ID_REC),
  INDEX FK_TBL_CLI_REC(TBL_CLIENTE_CLI_NUM_ID_CLI),
  INDEX FK_TBL_USU_REC(TBL_USUARIO_USU_NUM_ID_USU),
  INDEX FK_TBL_FP_REC(TBL_FORMA_PAGAMENTO_FP_NUM_ID_FP),
  INDEX FK_TBL_EMP_REC(TBL_EMPRESA_EMP_NUM_ID_EMP)
);

CREATE TABLE TBL_ORDEMSERVICO_OS (
  NUM_ID_OS INTEGER UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT,
  TBL_CLIENTE_CLI_NUM_ID_CLI INTEGER UNSIGNED ZEROFILL NOT NULL,
  TBL_EMPRESA_EMP_NUM_ID_EMP INTEGER UNSIGNED ZEROFILL NOT NULL,
  TBL_EQUIPAMENTO_EQUIP_NUM_ID_EQUIP INTEGER UNSIGNED ZEROFILL NOT NULL,
  TBL_USUARIO_USU_NUM_ID_USU INTEGER UNSIGNED ZEROFILL NOT NULL,
  TXT_TIPO_OS VARCHAR(20) NOT NULL,
  TXT_CONDICAO_PAGAMENTO_OS VARCHAR(20) NULL,
  DTH_ABERTURA_OS DATETIME NOT NULL,
  TXT_DADOSGERAIS_OS VARCHAR(100) NOT NULL,
  TXT_RECLAMACAO_OS VARCHAR(100) NOT NULL,
  DTA_PREVISAO_OS DATE NOT NULL,
  TXT_DEFEITO_OS TEXT NULL,
  TXT_RESOLUCAO_OS TEXT NULL,
  VAL_TOTAL_OS DOUBLE(8,2) NULL,
  VAL_DESCONTO_OS DOUBLE(8,2) NULL,
  VAL_FINAL_OS DOUBLE(8,2) NULL,
  DTH_ENCERRAMENTO_OS DATETIME NULL,
  DTA_FIMGARANTIA_OS DATE NULL,
  NUM_NFSE_OS INTEGER UNSIGNED NULL,
  TXT_CANCELAMENTO_OS TEXT NULL,
  NUM_KM_OS INTEGER UNSIGNED NULL,
  TXT_STATUS_OS VARCHAR(20) NULL,
  PRIMARY KEY(NUM_ID_OS),
  INDEX FK_TBL_USU_OS(TBL_USUARIO_USU_NUM_ID_USU),
  INDEX FK_TBL_EQUIP_OS(TBL_EQUIPAMENTO_EQUIP_NUM_ID_EQUIP),
  INDEX FK_TBL_EMP_OS(TBL_EMPRESA_EMP_NUM_ID_EMP),
  INDEX FK_TBL_CLI_OS(TBL_CLIENTE_CLI_NUM_ID_CLI)
);

CREATE TABLE TBL_ITEM_PECA_OS (
  NUM_ID_PECA_OS INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  TBL_USUARIO_USU_NUM_ID_USU INTEGER UNSIGNED ZEROFILL NOT NULL,
  TBL_ORDEMSERVICO_OS_NUM_ID_OS INTEGER UNSIGNED ZEROFILL NOT NULL,
  TBL_PECA_PEC_NUM_ID_PEC INTEGER UNSIGNED NOT NULL,
  NUM_QUANTIDADE_PECA_OS INTEGER UNSIGNED NULL,
  VAL_VALOR_PECA_OS DOUBLE(8,2) NULL,
  VAL_DESCONTO_PECA_OS DOUBLE(8,2) NULL,
  VAL_FINAL_PECA_OS DOUBLE(8,2) NULL,
  TXT_STATUS_PECA_OS VARCHAR(3) NULL,
  PRIMARY KEY(NUM_ID_PECA_OS),
  INDEX FK_TBL_PEC(TBL_PECA_PEC_NUM_ID_PEC),
  INDEX FK_TBL_OS(TBL_ORDEMSERVICO_OS_NUM_ID_OS),
  INDEX FK_TBL_USU(TBL_USUARIO_USU_NUM_ID_USU)
);

CREATE TABLE TBL_ITEM_SERVICO_OS (
  NUM_ID_SERVICO_OS INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  TBL_TECNICO_TEC_NUM_ID_TEC INTEGER UNSIGNED NOT NULL,
  TBL_USUARIO_USU_NUM_ID_USU INTEGER UNSIGNED ZEROFILL NOT NULL,
  TBL_SERVICO_SER_NUM_ID_SER INTEGER UNSIGNED NOT NULL,
  TBL_ORDEMSERVICO_OS_NUM_ID_OS INTEGER UNSIGNED ZEROFILL NOT NULL,
  DTH_INICIO_SERVICO_OS DATETIME NULL,
  DTH_TERMINO_SERVICO_OS DATETIME NULL,
  VAL_VALOR_SERVICO_OS DOUBLE(8,2) NULL,
  VAL_DESCONTO_SERVICO_OS DOUBLE(8,2) NULL,
  VAL_VALOR_FINAL_SERVICO_OS DOUBLE(8,2) NULL,
  TXT_STATUS_SERVICO_OS VARCHAR(20) NULL,
  PRIMARY KEY(NUM_ID_SERVICO_OS),
  INDEX FK_TBL_OS_ITOS(TBL_ORDEMSERVICO_OS_NUM_ID_OS),
  INDEX FK_TBL_SER_ITOS(TBL_SERVICO_SER_NUM_ID_SER),
  INDEX FK_TBL_USU_ITOS(TBL_USUARIO_USU_NUM_ID_USU),
  INDEX TBL_ITEM_SERVICO_OS_FKIndex4(TBL_TECNICO_TEC_NUM_ID_TEC)
);


